# This code downloads important weather condition data like GHI,DHI,Air temperature,etc. based on weather grids we created
# This will save 1 csv file for 1 grid.
# currently in my case I have 360 grids hence I will get 360 csv file containg weather data for each grid
# these csvs will be later used for creating one single csv file that contains weather data for each location(mentioned in weather_grids.csv) with timestamp
import requests
import pandas as pd
from pathlib import Path
import time
from dotenv import load_dotenv
import os

load_dotenv()
# Replace os.getenv("NREL_API_KEY") with your actual API key (generated by signing up on: https://developer.nrel.gov/signup/ )
API_KEY=os.getenv("NREL_API_KEY")

# Replacing following with your actual NREL website full name you submited while signing up
NREL_USER_FULL_NAME=os.getenv("NREL_USER_FULL_NAME")

# Replacing following with your actual NREL website email you submited while signing up
NREL_USER_EMAIL=os.getenv("NREL_USER_EMAIL")

GRID_FILE = Path("processed/weather_grids.csv")
OUT_DIR = Path("raw/weather")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# select a year to your likings
YEAR = "2006"

# select attributes to your likings
# checkout official website to see available options for year and attributes:
# https://developer.nrel.gov/docs/climate/ncdb/ncdb-4km-Hourly-CONUS-v1-0-0-RCP4-5-download/#request-parameters
ATTRS = ",".join([
    "ghi",
    "dni",
    "dhi",
    "air_temperature",
    "wind_speed",
    "solar_zenith_angle"
])

grids = pd.read_csv(GRID_FILE)
print("Total grids:", len(grids))

BASE_URL = (
    "https://developer.nrel.gov/api/climate/ncdb/v2/climate/"
    "ncdb-4km-Hourly-CONUS-v1-0-0-RCP4-5-download.csv"
    f"?api_key={API_KEY}"
)

headers = {
    "Content-Type": "application/x-www-form-urlencoded"
}

for i, row in grids.iterrows():
    lat = round(row.grid_lat, 3)
    lon = round(row.grid_lon, 3)

    fname = OUT_DIR / f"ncdb_{lat}_{lon}_{YEAR}.csv"
    if fname.exists():
        print(f"[SKIP] {fname.name}")
        continue

    print(f"[{i+1}/{len(grids)}] {lat}, {lon}")

    payload = {
        "wkt": f"POINT({lon} {lat})",
        "names": YEAR,
        "attributes": ATTRS,
        "utc": "false",

        # REQUIRED BY NCDB
        "full_name": NREL_USER_FULL_NAME,
        "email": NREL_USER_EMAIL,
        "affiliation": "Academic",#you should change this if your goal is not academic
        "reason": "Solar ML Research"#you should change this if your reason is something else
    }

    try:
        r = requests.post(
            BASE_URL,
            data=payload,
            headers=headers,
            timeout=180
        )
        r.raise_for_status()
        fname.write_bytes(r.content)
    except Exception as e:
        print(f"[ERROR] {lat},{lon} → {e}")

    time.sleep(1.2)

